FROM python:3.6

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends netcat-openbsd && \
    pip install --upgrade pip && pip install tox

ENTRYPOINT "/app/files/test_entrypoint.sh"
