#!/usr/bin/env sh

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-"localhost:9092"}
SCHEMAS_SERVER_URL=${SCHEMAS_SERVER_URL:-"http://localhost:8080/"}

echo $SCRIPTPATH

docker run --rm -t --network host --volume "${SCRIPTPATH}:/cwd" \
  -e KAFKA_BOOTSTRAP_SERVERS="$KAFKA_BOOTSTRAP_SERVERS" \
  -e SCHEMAS="$SCHEMAS_SERVER_URL" \
  pyrandall:latest \
  --config /cwd/config/test_env.json --dataflow /cwd $@
